### ISSUE TITLE
Installation requires installation of EBPM?

### ISSUE THREAD

**Issue by stephens999** [DongyueXie/stm#8]
need to change instructions to get user to install ebpm first?

library(devtools)
install_github("stephenslab/ebpm")

**Comment by stephens999** [comment]
also vebpm (which requires its own installation instructions)

**Comment by stephens999** [comment]
also requires wavethresh, Rfast

**Comment by DongyueXie** [comment]
added installation instruction of ebpm; added required packages from cran.
